=== Bulgwei/ADCSSetupHelper/conf/Config-CA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Config" type="ConfigType"/>

    <xsd:complexType name="ConfigType">
    	<xsd:sequence>
    		<xsd:element name="CA" type="CAType" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CAType">
    	<xsd:sequence>
    		<xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="ParentCa" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Type" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="StandaloneRootCA"/>
              <xsd:enumeration value="StandaloneSubordinateCA"/>
              <xsd:enumeration value="EnterpriseSubordinateCA"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="DistinguishedNameSuffix" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="DatabaseDirectory" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="LogDirectory" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="DsConfigDn" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="AllowAdministratorInteraction" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="Certificate" type="CertificateType" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="CertificateProfile" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value=""/>
              <xsd:pattern value="[Cc][Oo][Mm][Mm][Oo][Nn][Pp][Kk][Ii]"/>
              <xsd:pattern value="[De][Ee][Ff][Aa][Uu][Ll][Tt]"/>
              <xsd:pattern value="[Mm][Ii][Cc][Rr][Oo][Ss][Oo][Ff][Tt]"/>
              <xsd:pattern value="[Mm][Ii][Cc][Rr][Oo][Ss][Oo][Ff][Tt]-[Ll][Ee][Gg][Aa][Cc][Yy]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="RemoveMSFTExtensions" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="IncludeNonDefinedRDN" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
<xsd:element name="RemoveFromNTAuthCertificates" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="Crypto" type="CryptoType" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Policy" type="PolicyType" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Settings" type="SettingsType" minOccurs="1" maxOccurs="1"/>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CertificateType">
    	<xsd:sequence>
        <xsd:element name="ValidityPeriod" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value=""/>
              <xsd:pattern value="[Yy][Ee][Aa][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Oo][Nn][Tt][Hh][Ss]"/>
              <xsd:pattern value="[Ww][Ee][Ee][Kk][Ss]"/>
              <xsd:pattern value="[Dd][Aa][Yy][Ss]"/>
              <xsd:pattern value="[Hh][Oo][Uu][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Ii][Nn][Uu][Tt][Ee][Ss]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="ValidityPeriodUnits" minOccurs="1" maxOccurs="1">   
          <xsd:simpleType>
            <xsd:union>
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value=""/>
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:simpleType>
                <xsd:restriction base="xsd:integer"/>
              </xsd:simpleType>
            </xsd:union>
          </xsd:simpleType> 
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CryptoType">
    	<xsd:sequence>
        <xsd:element name="KspName" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="Microsoft Software Key Storage Provider"/>
              <xsd:enumeration value="Utimaco CryptoServer Key Storage Provider"/>
              <xsd:enumeration value="SafeNet Key Storage Provider"/>
              <xsd:enumeration value="nCipher Security World Key Storage Provider"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="EncryptionCspName" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="Microsoft Software Key Storage Provider"/>
              <xsd:enumeration value="Utimaco CryptoServer Key Storage Provider"/>
              <xsd:enumeration value="SafeNet Key Storage Provider"/>
              <xsd:enumeration value="nCipher Security World Key Storage Provider"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="KeyAlgorithm" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="RSA"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="KeyLength" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
              <xsd:enumeration value="8192"/>
              <xsd:enumeration value="4096"/>
              <xsd:enumeration value="2048"/>
              <xsd:enumeration value="1024"/>
              <xsd:enumeration value="512"/>
              <xsd:enumeration value="384"/>
              <xsd:enumeration value="256"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="Pkcs1Version" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="1.5"/>
              <xsd:enumeration value="2.1"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="SignatureHashAlgorithm" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Mm][Dd]5"/>
              <xsd:pattern value="[Ss][Hh][Aa]1"/>
              <xsd:pattern value="[Ss][Hh][Aa]256"/>
              <xsd:pattern value="[Ss][Hh][Aa]384"/>
              <xsd:pattern value="[Ss][Hh][Aa]512"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="PolicyType">
    	<xsd:sequence>
        <xsd:element name="PathLength" minOccurs="0" maxOccurs="1">
         <xsd:simpleType>
            <xsd:union>
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value=""/>
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:simpleType>
                <xsd:restriction base="xsd:integer">
                  <xsd:minInclusive value="0"/>
                  <xsd:maxInclusive value="10"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:union> 
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="IssuancePolicy" type="IssuancePolicyType" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="EnhancedKeyUsage" type="EnhancedKeyUsageType" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="EKUmArkCritical" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="IssuancePolicyType">
    	<xsd:sequence>
        <xsd:element name="Oid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Notice" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Url" type="xsd:anyURI" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="Description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="EnhancedKeyUsageType">
    	<xsd:sequence>
        <xsd:element name="Oid" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="SettingsType">
    	<xsd:sequence>
        <xsd:element name="AuditFilter" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:integer">
              <xsd:minInclusive value="0"/>
              <xsd:maxInclusive value="127"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="ValidityPeriodUnits" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="ValidityPeriod" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Yy][Ee][Aa][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Oo][Nn][Tt][Hh][Ss]"/>
              <xsd:pattern value="[Ww][Ee][Ee][Kk][Ss]"/>
              <xsd:pattern value="[Dd][Aa][Yy][Ss]"/>
              <xsd:pattern value="[Hh][Oo][Uu][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Ii][Nn][Uu][Tt][Ee][Ss]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AllowRenewalOnBehalfOf" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="Extensions" type="ExtensionsType" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="CRL" type="CRLType" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ExtensionsType">
    	<xsd:sequence>
        <xsd:element name="CDP" type="CDPType"  minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="AIA" type="AIAType"  minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CRLType">
    	<xsd:sequence>
        <xsd:element name="PeriodUnits" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Period" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Yy][Ee][Aa][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Oo][Nn][Tt][Hh][Ss]"/>
              <xsd:pattern value="[Ww][Ee][Ee][Kk][Ss]"/>
              <xsd:pattern value="[Dd][Aa][Yy][Ss]"/>
              <xsd:pattern value="[Hh][Oo][Uu][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Ii][Nn][Uu][Tt][Ee][Ss]"/>
            </xsd:restriction>
          </xsd:simpleType>        
        </xsd:element>
        <xsd:element name="OverlapUnits" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="OverlapPeriod" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Yy][Ee][Aa][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Oo][Nn][Tt][Hh][Ss]"/>
              <xsd:pattern value="[Ww][Ee][Ee][Kk][Ss]"/>
              <xsd:pattern value="[Dd][Aa][Yy][Ss]"/>
              <xsd:pattern value="[Hh][Oo][Uu][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Ii][Nn][Uu][Tt][Ee][Ss]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>        
        <xsd:element name="DeltaPeriodUnits" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="DeltaPeriod" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Yy][Ee][Aa][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Oo][Nn][Tt][Hh][Ss]"/>
              <xsd:pattern value="[Ww][Ee][Ee][Kk][Ss]"/>
              <xsd:pattern value="[Dd][Aa][Yy][Ss]"/>
              <xsd:pattern value="[Hh][Oo][Uu][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Ii][Nn][Uu][Tt][Ee][Ss]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>        
        <xsd:element name="DeltaOverlapUnits" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="DeltaOverlapPeriod" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Yy][Ee][Aa][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Oo][Nn][Tt][Hh][Ss]"/>
              <xsd:pattern value="[Ww][Ee][Ee][Kk][Ss]"/>
              <xsd:pattern value="[Dd][Aa][Yy][Ss]"/>
              <xsd:pattern value="[Hh][Oo][Uu][Rr][Ss]"/>
              <xsd:pattern value="[Mm][Ii][Nn][Uu][Tt][Ee][Ss]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CDPType">
    	<xsd:sequence>
        <xsd:element name="Protocol" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[hH][tT][tT][pP]"/>
              <xsd:pattern value="[fF][tT][pP]"/>
              <xsd:pattern value="[lL][dD][aA][pP]"/>
              <xsd:pattern value="[fF][iI][lL][eE]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="URL" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="AddToCrlCdp" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AddToCertificateCDP" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AddToFreshestCrl" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="PublishToServer" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="PublishDeltaToServer" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AddToCrlIdp" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AIAType">
    	<xsd:sequence>
        <xsd:element name="Protocol" minOccurs="1" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[hH][tT][tT][pP]"/>
              <xsd:pattern value="[fF][tT][pP]"/>
              <xsd:pattern value="[lL][dD][aA][pP]"/>
              <xsd:pattern value="[oO][cC][sS][pP]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="URL" type="xsd:string" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="AddToCertificateAia" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="AddToCertificateOcsp" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Bulgwei/ADCSSetupHelper/conf/FabRootCA.xml
<?xml version="1.0"?>
<!--
	Note:
		You should use an Editor with Syntax Highlighting for XML to edit this file
		Capable Applications include:
		- Notepad++
		- Visual Studio Code
		You may have serious trouble properly formatting the file wihout Syntax highlighting.
-->
<!--
	Description:
		Each Configuration File starts with a Config Node.
		This enables us to merge multiple Files into one single XML Configuration when loading
		The Config Node also contains Information on the Schema File that is used to verify the Configuration
		Each CA Configuration must contain at least one CA Node.
		The Node contains all Configuration Settings for a single CA.
		Though possible, I would personally not include more than one CA Node per file.
-->
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Config-CA.xsd">
	<CA>
		<!--
			Description:
				The Name Node specifies the Common Name of the CA
			Example:
				<Name>Fabrikam Root CA</Name>
				resolves to CN=Fabrikam Root CA in the CA Certificate
		-->
		<Name>Fabrikam-RootCA-V3</Name>
		<!--
			Description:
				The ParentCa Node specifies the Common Name of the CA that will sign
				the Certificate Signing Request for this CA.
				Therefore, this is only applicable if this CA is a Subordinate CA
			Default:
				Leave Empty or remove the entire Node if not needed
		-->
		<ParentCa></ParentCa>
		<!--
			Description:
				The Type Node specifies the CA Type
				Currently, only the following is supported:
				- StandaloneRootCA
				- EnterpriseSubordinateCA
		-->
		<Type>StandaloneRootCA</Type>
		<!--
			Description:
				The DistinguishedNameSuffix Node specifies additional Parameters for the CA Certificate Subject
				Valid fields contain: OU,O,L,S,C
			Example:
				<DistinguishedNameSuffix>OU=IT,O=Fabrikam,L=Munich,S=Bavaria,C=DE</DistinguishedNameSuffix>
			Default:
				Leave Empty or remove the entire Node if not needed
		-->
		<DistinguishedNameSuffix>OU=IT,O=ITSec,L=Vienna,S=Vienna,C=AT</DistinguishedNameSuffix>
		<!--
			Description:
				The DatabaseDirectory Node specifies the physical Path
				where to store the CA Database
			Default:
				Leave Empty if not needed
		-->
		<DatabaseDirectory></DatabaseDirectory>
		<!--
			Description:
				The LogDirectory Node specifies the physical Path
				where the CA Database Transaction Logs are stored
			Default:
				Leave Empty if not needed
		-->
		<LogDirectory></LogDirectory>
		<!--
			Description:
				The DsConfigDm Node specifieds the LDAP Path of the Configuration Partition
				of the Forest.
				The setting is mandatory if Type is StandaloneRootCA and LDAP is to be used
				The setting no effect when Type is EnterpriseSubordinateCA.
			Default:
				Leave Empty or remove the entire Node if not needed
		-->
		<DsConfigDn>CN=Configuration,DC=Fabrikam,DC=com</DsConfigDn>
		<!--
			Description:
				Ensure this is set to True if you use a HSM with Operator Card Set Protection
				or similar Mechanisms (like strong Private Key Protection) that requires interaction
				with the ADCS Service during the Start of the CA Service
			Default:
				The Setting must be either True or False
		-->
		<AllowAdministratorInteraction>False</AllowAdministratorInteraction>
		<!--
			Description:
				The Certificate Node describes Settings that apply to the CA Certificate
		-->
		<Certificate>
			<!--
				Description:
					The ValidityPeriod and ValidityPeriodUnits Nodes specify the Validity
					Period for a CA Certificate. This only applies to Root CA Certificates, 
					as or Sub CA Certificates this is given by the Parent CA
					Thus, no effect when Type is EnterpriseSubordinateCA
				Default:
					For a Root CA: 8 Years
					For a Subordinate CA: Leave Empty or remove the entire Certificate Node
			-->
			<ValidityPeriod>Years</ValidityPeriod>
			<ValidityPeriodUnits>12</ValidityPeriodUnits>
		</Certificate>
		<!--
			Description:
				The CertificateProfile Node describes a specific Certificate Profile to be used
				for the CA Certificate. It currently can only be set to "CommonPki", which will ensure 
				that our CA Certificate will be strictly compliant to the Certificate Profile of the 
				Common PKI Standard which is mainly used in Germany and recommended by the Authorities
			Default:
				Leave Empty or remove the Node if not needed
		-->
		<CertificateProfile></CertificateProfile>
		<!--
			Description:
				The RemoveMSFTExtensions Node specifies whether to remove the Microsoft Specific
				Extensions in the CA Certificate (CA Version, Previous CA Certificate Hash, 
				Certificate Template Information). In most Cases, this is not needed. There were times
				when Legacy Applications had trouble interpreting these Extensions correctly.
			Default:
				Set to False or remove the Node if not needed	
		-->
		<RemoveMSFTExtensions>False</RemoveMSFTExtensions>
		<!--
			Description:
				The RemoveFromNTAuthCertificates Node specifies whether the CA Certificate shall be removed
				from the Active Directory NTAuthCertificates Store after Deployment, or not.
				A Common reason to remove the Certificate is that it cannot be used for Certificate-based Logon
				(like Smart Card Logon) anymore, which may prevent the CA from taking over Active Directory.
			Note:
				Removing the CA Certificate from NTAuthCertificates will disable the following Services
				and Features:
					- Enroll on behalf of
					- Certificate-based Logon with Microsoft Network Policy Server (VPN, 802.1X)
					- Smart Card Logon
					- Windows Hello for Business
			Default:
				Set to False or remove the Node if not needed	
		-->
		<RemoveFromNTAuthCertificates>False</RemoveFromNTAuthCertificates>
		<Crypto>
			<!--
				Description:
					The KspName Node specifies the Key Storage Provider to be used for the CA Certificate
				Examples:
					- Microsoft Software Key Storage Provider
					- Utimaco CryptoServer Key Storage Provider
					- SafeNet Key Storage Provider
					- nCipher Security World Key Storage Provider
				Note:
					Do NOT append the "RSA#" Prefix
				Default:
					Microsoft Software Key Storage Provider
			-->
			<KspName>Microsoft Software Key Storage Provider</KspName>
			<!--
				Description:
					The EncryptionCspName Node specifies the Key Storage Provider to be used for the CA 
					Exchange Certificate. If using a Hardware Security Module (HSM), the CA will by default
					use the same Key Storage Provider for the private Keys of CA Exchange Certificate.
					It might be a good choice to change this to a the Microsoft Software KSP to avoid HSM 
					issues like the partition filling up. The CA Exchange Certificate may be recreated 
					every two weeks aith a new Key Pair. Also, you might get avoidable OCC prompts when running
					the ADCS Assessment Data Collection Tool.
				Default:
					Leave Empty or remove the Node if not needed
			-->
			<EncryptionCspName>Microsoft Software Key Storage Provider</EncryptionCspName>
			<!--
				Description:
					The KeyAlgorithm Node specifies Cryptographic Algorithm that is used to create the 
					Key Pair for the CA Certificate. May be RSA or ECC, but please make sure that the 
					Key Storage Provider specified under KspName supports it.
				Default:
					RSA
			-->
			<KeyAlgorithm>RSA</KeyAlgorithm>
			<!--
				Description:
					The KeyLength Node specifies Key Length used for the Key Pair for the CA Certificate.
					For RSA, this may be 1024, 2048, 4096, 8192
					For ECC, this may be 256, 384, 512
				Default:
					4096
			-->
			<KeyLength>4096</KeyLength>
			<!--
				Description:
					The Pkcs1Version Node specifies the Signature Algorithm (PKCS#1) to use for issued Certificates
					May be 1.5 or 2.1
					From a security perspective, PKCS#1 2.1 is recommended.
					However, many vendors (like Cisco) have not implemented PKCS#1 2.1, thus
					their devices cannot understand certificates from a CA that signs with 2.1
					For compatibility reasons, we will have to fall back to 1.5 in most cases
					There are working attacks on 1.5, which are currently mitigated within
					the actual products that use Certificates
				Default:
					1.5
			-->
			<Pkcs1Version>1.5</Pkcs1Version>
			<!--
				Description:
					The SignatureHashAlgorithm Node specifies the Signatuee Hash Algorithm to use for issued Certificates
					May be MD5, SHA1, SHA256, SHA384, SHA512
					See https://msdn.microsoft.com/de-de/library/system.security.cryptography.hashalgorithmname(v=vs.110).aspx for more information.
				Default:
					SHA256
			-->
			<SignatureHashAlgorithm>SHA256</SignatureHashAlgorithm>
		</Crypto>
		<!--
			Description:
				The Policy Node specifies Policy Settings that apply to the CA Certificate of our CA
				These are included in the Certificate Signing Request (CSR) of the CA Certificate
				They include
					- Path Length Constraints
					- Issuance Policies (like a Certificate Practice Statement)
					- Application Policies (aka Enhanced Key Usage Constraints)
			Note:
				Naming Constraints are not implemented yet
		-->
		<Policy>
			<!--
				Description:
					The PathLength Node specifies the Path Length Constraint that applies to the CA.
					A Path Length Constraint describes how many CAs may follow below this one further down in
					the Hierarchy. For a 2-Tier Deployment, the Root CA usually gets "1" and the Subordinate CA get "0"
				Note:
					- PathLength on a Root CA Certificate will result in the Value being written into the 
					  CAPathLength Registry Key of the CA (not included in the CA certificate but honored by the Policy Module)
					- PathLength on a Subordinate CA Certificate will result in	the Value being written into the CSR
				Default:
					Leave Empty or remove the Node if not needed
			-->
