=== Bulgwei/ADCSSetupHelper/conf/Config-Engagements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Config" type="ConfigType"/>

    <xsd:complexType name="ConfigType">
    	<xsd:sequence>
    		<xsd:element name="Engagement" type="EngagementType" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="EngagementType">
    	<xsd:sequence>
            <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    		<xsd:element name="GenericTerms" type="GenericTermsType"></xsd:element>
            <xsd:element name="Chapters" type="ChaptersType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="GenericTermsType">
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element name="Term" type="TermType"/>
      </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="TermType">
      <xsd:sequence>
        <xsd:element name="Placeholder" type="xsd:string"/>
        <xsd:element name="ReplaceWith" type="xsd:string"/>
        <xsd:element name="SearchInHeader">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ChaptersType">
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element name="Chapter" type="ChapterType"/>
      </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="ChapterType">
      <xsd:sequence>
        <xsd:element name="Name">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="DeploymentGuide"/>
              <xsd:enumeration value="OperationsGuide"/>
              <xsd:enumeration value="MaintenanceGuide"/>
              <xsd:enumeration value="SecurityGuide"/>
              <xsd:enumeration value="MonitoringGuide"/>
              <xsd:enumeration value="TroubleShootingGuide"/>
              <xsd:enumeration value="UsageGuide"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="Enabled">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Bulgwei/ADCSSetupHelper/conf/Config-Engagements.xml
<?xml version="1.0"?>

<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Config-Engagements.xsd">
    <Engagement>
        <Name>OAADCS</Name>
        <GenericTerms>
            <Term>
                <Placeholder>EngagementName</Placeholder>
                <ReplaceWith>Onboarding Accelerator - Deployment and Migration Assistance for Active Directory Certificate Services</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementShortName</Placeholder>
                <ReplaceWith>Onboarding Accelerator AD CS</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementAbbreviation</Placeholder>
                <ReplaceWith>OAADCS</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>DocTitle</Placeholder>
                <ReplaceWith>OnSite Engagement Documentation</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
        </GenericTerms>
        <Chapters>
            <Chapter>
                <Name>DeploymentGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>OperationsGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MaintenanceGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>SecurityGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MonitoringGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>TroubleShootingGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>UsageGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
        </Chapters>
    </Engagement>
    <Engagement>
        <Name>PAS</Name>
        <GenericTerms>
            <Term>
                <Placeholder>EngagementName</Placeholder>
                <ReplaceWith>Public Key Infrastructure (PKI) Advisory Service</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementShortName</Placeholder>
                <ReplaceWith>PKI Advisory</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementAbbreviation</Placeholder>
                <ReplaceWith>PAS</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>DocTitle</Placeholder>
                <ReplaceWith>OnSite Engagement Documentation</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
        </GenericTerms>
        <Chapters>
            <Chapter>
                <Name>DeploymentGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>OperationsGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MaintenanceGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>SecurityGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>MonitoringGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>TroubleShootingGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>UsageGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
        </Chapters>
    </Engagement>
    <Engagement>
        <Name>DSE</Name>
        <GenericTerms>
            <Term>
                <Placeholder>EngagementName</Placeholder>
                <ReplaceWith>Microsoft Dedicated Support Engineer (DSE)</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementShortName</Placeholder>
                <ReplaceWith>Microsoft DSE</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementAbbreviation</Placeholder>
                <ReplaceWith>MS DSE</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>DocTitle</Placeholder>
                <ReplaceWith>PKI Setup Documentation</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
        </GenericTerms>
        <Chapters>
            <Chapter>
                <Name>DeploymentGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>OperationsGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MaintenanceGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>SecurityGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MonitoringGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>TroubleShootingGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>UsageGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
        </Chapters>
    </Engagement>
    <Engagement>
        <Name>POP-ADCS</Name>
        <GenericTerms>
            <Term>
                <Placeholder>EngagementName</Placeholder>
                <ReplaceWith>Proactive Operations Program (POP) Active Directory Certificate Services (ADCS)</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementShortName</Placeholder>
                <ReplaceWith>POP - ADCS</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>EngagementAbbreviation</Placeholder>
                <ReplaceWith>POP-ADCS</ReplaceWith>
                <SearchInHeader>False</SearchInHeader>
            </Term>
            <Term>
                <Placeholder>DocTitle</Placeholder>
                <ReplaceWith>PKI Deployment Documentation</ReplaceWith>
                <SearchInHeader>True</SearchInHeader>
            </Term>
        </GenericTerms>
        <Chapters>
            <Chapter>
                <Name>DeploymentGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
            <Chapter>
                <Name>OperationsGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MaintenanceGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>SecurityGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>MonitoringGuide</Name>
                <Enabled>True</Enabled>
            </Chapter>
            <Chapter>
                <Name>TroubleShootingGuide</Name>
                <Enabled>False</Enabled>
            </Chapter>
        </Chapters>
    </Engagement>
</Config>
