=== Bulgwei/ADCSSetupHelper/conf/Config-GenericTerms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Config" type="ConfigType"/>

    <xsd:complexType name="ConfigType">
    	<xsd:sequence>
    		<xsd:element name="GenericTerms" type="GenericTermsType" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="GenericTermsType">
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element name="Term" type="TermType"/>
      </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="TermType">
      <xsd:sequence>
        <xsd:element name="Placeholder" type="xsd:string"/>
        <xsd:element name="ReplaceWith" type="xsd:string"/>
        <xsd:element name="SearchInHeader">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:pattern value="[Tt][Rr][Uu][Ee]"/>
              <xsd:pattern value="[Ff][Aa][Ll][Ss][Ee]"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Bulgwei/ADCSSetupHelper/conf/Config-GenericTerms.xml
<?xml version="1.0"?>

<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Config-GenericTerms.xsd">
    <GenericTerms>
        <Term>
            <Placeholder>CheckBox-True</Placeholder>
            <ReplaceWith>Checked</ReplaceWith>
            <SearchInHeader>False</SearchInHeader>
        </Term>
        <Term>
            <Placeholder>CheckBox-False</Placeholder>
            <ReplaceWith>Unchecked</ReplaceWith>
            <SearchInHeader>False</SearchInHeader>
        </Term>
        <Term>
            <Placeholder>YesNo-True</Placeholder>
            <ReplaceWith>Yes</ReplaceWith>
            <SearchInHeader>False</SearchInHeader>
        </Term>
        <Term>
            <Placeholder>YesNo-False</Placeholder>
            <ReplaceWith>No</ReplaceWith>
            <SearchInHeader>False</SearchInHeader>
        </Term>
    </GenericTerms>
</Config>
